# config/packages/fos_user.yaml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "no-reply@lsacbucuresti.ro"
        sender_name: "no-reply@lsacbucuresti.ro"

    registration:
        form:
            type: App\Form\RegistrationType
        confirmation:
            enabled: true